### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by suvamM** [microsoft/sarif-pattern-matcher#121]
I am facing issues building the solution---running `BuildAndTest.cmd` from powershell throws a bunch of errors, which seem to highlight missing dependencies. Could you kindly enumerate the dependencies for the project in the documentation? Thanks!

**Comment by eddynaka** [comment]
Hi @suvamM , we have this: https://github.com/microsoft/sarif-pattern-matcher/blob/main/CONTRIBUTING.md.

Check if that is enough. Otherwise, post the console output so we can help and improve the docs.


Thank you!
