### ISSUE TITLE
PlugIns build don't move build output path and test results locations

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-pattern-matcher#22]
These are emitted within each plugin directory currently. Can we change relevant targets files to redirect to the official build location?

@eddynaka

**Comment by eddynaka** [comment]
Sure! The idea would be to move to the bld folder, right?

**Comment by michaelcfanning** [comment]
Right! All intermediates and build outputs are stored somewhere with \bld\

**Comment by eddynaka** [comment]
Looking at the obj, looks like since we are using the flag to generate the nupkg while building, it generates those files there. Right now, we have configured the intermediate paths.

**Comment by eddynaka** [comment]
Removing the generation automatically does not change those files. The real files needed to build are being transferred. Don't know if we need to worry about those.
For the test results, I will check how to move those.

**Comment by eddynaka** [comment]
Added a .runsettings file moving to bld\TestResults
