### ISSUE TITLE
GoogleGCMServiceAccountValidator casing incorrect and fingerprint is wrong

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-pattern-matcher#331]
@eddynaka , @jameswinkler , this is a small fix but high priority

The correct casing of this rule name is GoogleGcmServiceAccountValidator. In .NET, you never case more than two letters in sequence as upper-case.

Also, the fingerprint for this check is broken. Resource is not the right property to use. A 'resource' is a sub-component of a container. So, a database is a resource of a database server.
 
This rule in general looks weak. What's the insecurity here? If we can't detect an exposure of interest, that can be validated, please just consider deleting this check for now.

**Comment by eddynaka** [comment]
I will exclude GCM since we are not capturing anything relevant and we can't validate.
