### ISSUE TITLE
Please add tests or delete rules for Hockey app and Facebook app credentials

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/sarif-pattern-matcher#332]
@jameswinkler, @eddynaka

We have no meaningful tests for these checks. Please review these rules for value. And build them out if they should be retained or delete them if they are weak.

**Comment by eddynaka** [comment]
I will add more tests to facebookAppCredentials, since that has a validator and we are getting matches.

**Comment by eddynaka** [comment]
I will remove HockeyApp.
