### ISSUE TITLE
Verify checksum for new GitHub PAT

### ISSUE THREAD

**Issue by jameswinkler** [microsoft/sarif-pattern-matcher#365]
The new GitHub PAT described here:

https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

... comes with a checksum in the last 6 characters.  Use this in static validation to reduce false positives.

We may be able to calculate CRC32 using existing code in the internal repo, here: 
\src\Plugins\Security.Internal\SEC101_102.AdoPatValidator.cs

This library may be useful: 

ICSharpCode.SharpZipLib.Checksum;

Search Nuget for "SharpZipLib"

Other useful code:

var crc32 = new Crc32();
byte[] byteArray = Encoding.ASCII.GetBytes(pat);
crc32.Update(byteArray);
string testString = crc32.Value.ToString();

string paddedIntendedChecksum = crc32.Value.ToString().PadLeft(6, '0');

if (paddedIntendedChecksum != checksum)
{
    return ValidationState.NoMatch;
}

**Comment by eddynaka** [comment]
We implemented it internally.
