### ISSUE TITLE
Current version of SPAM is not generating context region

### ISSUE THREAD

**Issue by eddynaka** [microsoft/sarif-pattern-matcher#676]
## Description

When using SPAM + SarifLogger, given the correct dataToInsert flags, I would expect to get the region/context region snippet. But, right now, the tool is not generating it.

## Reproduction

https://github.com/microsoft/sarif-pattern-matcher/pull/675

## Expectation

Generate region/context region when a result is generated.

## Actual

Only the region is being generated.

@michaelcfanning @marmegh @suvamM @cfaucon @HulonJenkins

**Comment by michaelcfanning** [comment]
Fixed.
