### ISSUE TITLE
`force` option not supported

### ISSUE THREAD

**Issue by suvamM** [microsoft/sarif-pattern-matcher#734]
The `--force` command does not seem to be supported anymore. The `--help` option should display the substitute. When the output SARIF log is already present, the error message recommends using the `--force` command, and this needs to be updated as well.

**Comment by michaelcfanning** [comment]
This may be hard to discover in our release notes. :) To make command-lines more efficient, we collapse all output file arguments in a single, semicolon delimited list, e.g. the following will force an overwrite and also pretty print the log.
~~~
--log ForceOverwrite;PrettyPrint
~~~
